### ISSUE TITLE
User ids / sessions

### ISSUE THREAD

**Issue by MDevolution** [cheshire-cat-ai/core#169]
I'm creating a telegram bot that interacts with cheshire cat.
How can I separate chats based on users? it seems that the cat's memory is shared.

Below the main function and the function called when the bot receives a message

```
async def generate_response(update: Update, context: ContextTypes.DEFAULT_TYPE):
    try:
        async with websockets.connect('ws://localhost:1865/ws') as websocket:
            print('User: ' + update.message.text)
            await websocket.send('{"text":"' + update.message.text + '"}')
            cat_response = await websocket.recv()
            print(cat_response)
            cat_json = json.loads(cat_response)
            response = cat_json['content']
            print('Cheshire Cat: ' + cat_json['content'])
    
    except websockets.exceptions.InvalidURI:
        print("Invalid URI provided. Please provide a valid URI.")

    except websockets.exceptions.InvalidStatusCode:
        print("Invalid status code received. Please check your connection.")

    except websockets.exceptions.WebSocketProtocolError:
        print("Websocket protocol error occurred. Please check your connection.")

    except websockets.exceptions.ConnectionClosedOK:
        print("Connection successfully closed.")

    except Exception as e:
        print("An error occurred:", e)
        
        
    # Send message back
    await context.bot.send_message(chat_id=update.effective_chat.id, text=response)
```

```
if __name__ == '__main__':
    
    # Set Telegram bot
    application = ApplicationBuilder().token(os.getenv("TELEGRAM_BOT_TOKEN")).build()

    # Message handler
    generate_response_handler = MessageHandler(filters.TEXT & (~filters.COMMAND), generate_response)
    application.add_handler(generate_response_handler)

    # Start bot
    application.run_polling()
```

the message received by the bot contains the following information and also the user's unique id.

`Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Michele', id=111067982, type=<ChatType.PRIVATE>, username='mdevo95'), date=datetime.datetime(2023, 4, 25, 7, 48, 3, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Michele', id=111067982, is_bot=False, language_code='it', username='mdevo95'), group_chat_created=False, message_id=296, supergroup_chat_created=False, text='mi chiamo michele'), update_id=583213452)`

How can I divide the cat's memory so that all the information refers to the specific user?

**Comment by pieroit** [comment]
Hi @MDevolution thanks, we should go in two steps:

## Step 1: make messages user specific

The cat sends messages like this:

```json
{
    "text": "user prompt"
}
``` 

We can extend the message in this way:

```json
{
    "text": "user prompt"
    "user_id": "alice"
}
```
If there is no `user_id` key in the json we assume it's `"user_id" : None` or `"user_id" : "nouser"`

We should somehow communicate also `user_id` when uploading a file to the rabbit hole

## Step 2: user specific conversation

Cat recent conversation history is stored [here](https://github.com/pieroit/cheshire-cat/blob/main/core/cat/looking_glass/cheshire_cat.py#L101) and that simple string should become a dictionary

```json
{
    "user_1": ... //recent conversation history with user user_1,
    "user_2": ... //recent conversation history with user user_2,
    ...
}
```
Also would be good if instead of a string for the single conversation history, we have an array of dictionaries

```json
[
    { "who": "human", "text": "....." },
    { "who": "cat", "text": "....." },
    { "who": "human", "text": "....." },
    ...
    ...
]
```

This may be the first part to start editing for a PR

## Step 3: user specific memories

* When memories [get stored](https://github.com/pieroit/cheshire-cat/blob/main/core/cat/looking_glass/cheshire_cat.py#L313) we should add to metadata for Qdrant a `user_id` key so memories are user based
* When memories [are retrieved](https://github.com/pieroit/cheshire-cat/blob/main/core/cat/looking_glass/cheshire_cat.py#L254) we should filter by `user_id` so only user specific memories are retrieved

## Step 4: let plugins do the work

let plugins access data structures for storing and searching memories so they can allow more creative users (some form of organizational ACL for example)

## Step 5: future improvements

In a future version we can better deal with different users by introducing actual user models and endpoints with full blown session based cookies/headers, as suggested in #62 .
To be honest I don't know if we are better off directly starting with [Sessions](https://jordanisaacs.github.io/fastapi-sessions/) and [Users](https://github.com/fastapi-users/fastapi-users) in fastAPI style and then push them down to the cat. Looks overkill to me, but I may be wrong.

@MDevolution what do you think? also a ping for @Mte90 @EugenioPetulla @antonioru @umbertogriffo @peppicus

**Comment by EugenioPetulla** [comment]
Thinking a lot about a "session" system as starting point. This will permit us to implements different session for the same user in the future (chatGPT style).

IMHO at the moment sessions are enough to build upon.

This:
```
{
    "text": "user prompt"
    "user_id": "alice"
}
```

Sould be:
```
{
    "text": "user prompt"
    "session": session_ID
}
```

In this way we can postpone users and let them be just a "collection of sessions + auth".

Taking this Telegram bot as reference, it will be easy to add a super  light db or a simple reference file in order to link a user to a session directly in the middleware. User auth and security relies upon telegram or the Bot service  ;)

**Comment by pieroit** [comment]
> Sould be:
> 
> ```
> {
>     "text": "user prompt"
>     "session": session_ID
> }
> ```

That is not enough for memory and file/url uploads, as they span on a longer time range than a session and are user specific.

> Taking this Telegram bot as reference, it will be easy to add a super light db or a simple reference file in order to link a user to a session directly in the middleware. User auth and security relies upon telegram or the Bot service ;)

Agree on having user management outside, at least on the short/medium term. In any case `user_id` has to be communicated as `session_id` is not enough :(

**Comment by pieroit** [comment]
> I don't understand how do I recall the different memories based on the users? Do I need to create hooks?

During memory retrieval, you should be able to pass additional filters via `metadata` arg to the function. See how it goes into `query_filter` param here:
https://github.com/pieroit/cheshire-cat/blob/main/core/cat/memory/vector_memory.py#L92

Does it not work?
 
> Thanks for the support

Thank you for contributing!
Ask me anything, I work on this all day

**Comment by EugenioPetulla** [comment]
> 

Maybe I was not able to explain myself but I'm not referring to session as "classic session" but as a "chat session" with the cat. In this case the chat could be potentially retrieved and opened as much as you want. It's the same concept of ChatGPT, where you have X chats per user and the single chat has his own context and memory. In this case the user it's not necessary from the start and you can implement this concept whenever you want.

Maybe we can simply call it `chat_id` 😄

**Comment by pieroit** [comment]
Updating the proposal with @zioproto suggestion:
- the cat does not manage users, but keeps memory and conversations separated by user_id
- users can be managed and authenticated via a separated container using [Keycloak](https://www.keycloak.org/getting-started/getting-started-docker) and [fastapi-third-party-auth](https://fastapi-third-party-auth.readthedocs.io/en/latest/).

This looks good to me because allows authentication without the boilerplate. As we need to focus on the AI part and not on application logic, the proposal strikes a good balance.

**Comment by AlboCode** [comment]
Hi everyone,
can I help with this task? or someone is already dealing with it?

**Comment by pieroit** [comment]
@AlboCode it would be great to work on this, the situation is a little stale (because it's a lot of work :)

If you come to the discord we can have an open mic and I present you several options

**Comment by AlboCode** [comment]
yes, I'm down for it!

**Comment by pieroit** [comment]
thanks @AlboCode, we have a prototype for users in the cat.
Let's test this stuff and iterate in the future ;)
Closing this for now
