### ISSUE TITLE
OpenAI is deprecating `text-davinci-003`

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#464]
Our default [`model_name`on GPT3](https://github.com/cheshire-cat-ai/core/blob/a1262d3cf3abe7cf31cb79e8bcee7343339b6275/core/cat/factory/llm.py#L99) `text-davinci-003` should be substituted with `gpt-3.5-turbo-instruct`
More info [here](https://openai.com/blog/gpt-4-api-general-availability) (section on Deprecation)

It's a simple and small PR for first comers, please test it manually before submitting :)

**Comment by rojin254** [comment]
Hey I want to contribute but was wondering if I should additionally change model_name in LLMOpenAIConfig as well since it will also be [deprecating soon](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#:~:text=GPT%2D35%2DTurbo%200301%20and%20GPT%2D4%200314%20retirement) or should i leave it be since [Upon retirement, deployments will automatically be upgraded to the default version at the time of retirement](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#:~:text=Upon%20retirement%2C%20deployments%20will%20automatically%20be%20upgraded%20to%20the%20default%20version%20at%20the%20time%20of%20retirement)

**Comment by pieroit** [comment]
> Hey I want to contribute but was wondering if I should additionally change model_name in [LLMOpenAIConfig](https://github.com/cheshire-cat-ai/core/blob/a1262d3cf3abe7cf31cb79e8bcee7343339b6275/core/cat/factory/llm.py#L142C5-L142C5) as well since it will also be [deprecating soon](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#:~:text=GPT%2D35%2DTurbo%200301%20and%20GPT%2D4%200314%20retirement) or should i leave it be since [Upon retirement, deployments will automatically be upgraded to the default version at the time of retirement](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#:~:text=Upon%20retirement%2C%20deployments%20will%20automatically%20be%20upgraded%20to%20the%20default%20version%20at%20the%20time%20of%20retirement)

Welcome!
Yep let's update also Azure

**Comment by pieroit** [comment]
Merging @rojin254 soon
