### ISSUE TITLE
[Feature] Consisten methods for static url and path

### ISSUE THREAD

**Issue by nicola-corbellini** [cheshire-cat-ai/core#469]
**Describe the solution you'd like**
The Cat provides two methods for accessing the static [url](https://github.com/cheshire-cat-ai/core/blob/a24934adcc0d9c982269003864ec1bc13645ddd7/core/cat/looking_glass/cheshire_cat.py#L388) and the static [path](https://github.com/cheshire-cat-ai/core/blob/a24934adcc0d9c982269003864ec1bc13645ddd7/core/cat/looking_glass/cheshire_cat.py#L392).
One is ending with a slash (i.e. `static/`) and the other isn't.
For consistency, the should both end with or without.

**Comment by rojin254** [comment]
I think it would be better to add a trailing "/" to the URL  since few existing path variables already needs to end with a "/" to work.
eg: [here self.__path should end with / to work](https://github.com/cheshire-cat-ai/core/blob/a24934adcc0d9c982269003864ec1bc13645ddd7/core/cat/mad_hatter/plugin.py#L143)
