### ISSUE TITLE
Ollama integration

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#487]
[Ollama](https://ollama.ai/) is at the moment the best candidate to be a local LLM runner for the cat.
It has both easy to use CLI & http API, already dockerized, GPU ready.

In the next weeks it will be possible to offer our community a ready `docker-compose.yml` to bring up the cat (in [its own docker image](https://github.com/cheshire-cat-ai/core/pull/484)), qdrant and ollama each in its own container, everything preconfigured and ready to go. (not sure what to do with the embedder).

A first step towards this is to have a `LLMOllamaConfig` in the [LLM factory](https://github.com/cheshire-cat-ai/core/blob/main/core/cat/factory/llm.py), based on langchain class [llms.Ollama](https://python.langchain.com/docs/integrations/llms/ollama) and pointing to `http://localhost:11434`.

Let's see afterwards if it is the case to add also `ChatOllama` and `OllamaEmbeddings` via langchain

Please comment the issue if you want it to be assigned to you :)

**Comment by valentimarco** [comment]
I'd like to work in it

**Comment by valentimarco** [comment]
Now we have support for Ollama: ab782464a6df2325d2172bce5e73a8580de4ae80.
I have multiple questions:
1. The Ollama class from langchain support multiple params in addition to the default ones that i don't know if will be usefull: [Ollama langchain params](https://api.python.langchain.com/en/latest/llms/langchain.llms.ollama.Ollama.html)
2. The implementaion of the factory is under CustomLLM, this is because i wanna implement a function to pull the llm image from ollama's library. Right now, after installing ollama (even in the docker image) you need to pull the image using the command ```ollama pull <modelname>:<tag>```. 
The function will have this pipeline: after getting the settings from the frontend, it will send a request to the endpoint <ollama_machine_ip>/api/pull and trying to download the desired.
