### ISSUE TITLE
[BUG] Websocket messages are mixed

### ISSUE THREAD

**Issue by Pingdred** [cheshire-cat-ai/core#488]
**Describe the bug**
At the moment there is a unique [queue](https://github.com/cheshire-cat-ai/core/blob/1e72089959efc5342d06d6a4e1c840c811efe469/core/cat/looking_glass/cheshire_cat.py#L74C29-L74C29) for all the ws messages, so if the are multiple websocket connection open is not predictable to which connection the messages are sent, because each ws connection read from the same queue.

**To Reproduce**
1. Open two ws connection, ad example open the admin in two different browser tab;
2. Do something that send a notification, like upload a document;

**Expected behavior**
Notifications sent while the document uploading should only be shown in the tab where the document is uploaded.

A possible solution is to make the queue](https://github.com/cheshire-cat-ai/core/blob/1e72089959efc5342d06d6a4e1c840c811efe469/core/cat/looking_glass/cheshire_cat.py#L74C29-L74C29) a dictionary of queue using as key for each queue the user id.

**Comment by pieroit** [comment]
@AlboCode please comment here so I can assign also to you :)

**Comment by AlboCode** [comment]
here I am 😄

**Comment by AlboCode** [comment]
I have some doubt if the user_id is the solution. When a document is uploaded, we don't know where is the connected user 🤔 
Only when a message is sent on the WS there is also the user_id property.
Is there a way to set a "SESSION_ID" in the header when the user connect to the websocket?

**Comment by pieroit** [comment]
> I have some doubt if the user_id is the solution. When a document is uploaded, we don't know where is the connected user 🤔 Only when a message is sent on the WS there is also the user_id property.

At the moment declarative memory is general (not segregated by users) but we can easily extend the http endpoints to accept a `user_id` param. (As it happens in the `memory/recall` endpoint)
This tests make it clear:
https://github.com/cheshire-cat-ai/core/blob/09d5e5c6e5b91e919c740fc7ed434854c35f7bde/core/tests/routes/memory/test_memory_by_user.py

> Is there a way to set a "SESSION_ID" in the header when the user connect to the websocket?
I don't understand this can you clarify?

**Comment by AlboCode** [comment]
my doubt was, when there is just a connected web socket listening for notifications how do we know the connected user_id? we send all the notifications to the default user id (user) only in a broadcast way? 
maybe I'm missing some parts

**Comment by giovannialbero1992** [comment]
@AlboCode the message is already sent in a proper way with `send_personal_message` method.
The problem here is that in the socket they are sending even information about activities triggered by other user.
An idea could be to use an header (or even extend the endpoint `/ws` with something like `/ws/{token}` to recognize the user to send the message. At this point any API call performed by cheshire-cat's admin could add this token in any request, like a header, and so fire the method `send_personal_message` only if there is matching with the token. BTW if I'm getting the point we could extend the message enqueued in `ws_messages` adding a property token passed by the methods that are calling `send_ws_message` and if a token is not set, means that the message must be sent in a broadcast way and so we can call the method `broadcast` instead of `send_personal_message`.

**Comment by pieroit** [comment]
@giovannialbero1992 at the moment the `user_id` is sent as a key directly to the websocket message.

I'm confused on how to have "sessions" tha tin the framework should translate to different instances of the WorkingMemory (which is the only object storing temporary user based information like convo history)
