### ISSUE TITLE
Problema with Ollama

### ISSUE THREAD

**Issue by Leresyn** [cheshire-cat-ai/core#548]
Hi, I've been trying to connect ollama to the cheshire cat but I can't figure out how to make it work. I have Ollama installed on macos and would like to try different models (llama2, mistral, zephyr, etc...). Which URL should I enter in the Base URL section of the Ollama menu in settings? Does Ollama need to be activated via docker? Thank you for your work and for the project.

**Comment by pieroit** [comment]
> Hi, I've been trying to connect ollama to the cheshire cat but I can't figure out how to make it work. I have Ollama installed on macos and would like to try different models (llama2, mistral, zephyr, etc...). Which URL should I enter in the Base URL section of the Ollama menu in settings? Does Ollama need to be activated via docker? Thank you for your work and for the project.

I used it yesterday with `zephyr`!
You need to use `<ip-address>:11434` and below, write the name of the model you pulled.
Let me know, closign the issue

**Comment by Leresyn** [comment]
If I Open Ollama and pull Zephyr through Terminal with (Ollama pull zephyr) and I put http://127.0.0.1:11434 in the Base URL and Zephyr in model. I start the chat and it gives me this error: 

HTTPConnectionPool(host='127.0.0.1', port=11434): Max retries exceeded with url: /api/generate/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd525f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by pieroit** [comment]
> If I Open Ollama and pull Zephyr through Terminal with (Ollama pull zephyr) and I put http://127.0.0.1:11434 in the Base URL and Zephyr in model. I start the chat and it gives me this error:
> 
> HTTPConnectionPool(host='127.0.0.1', port=11434): Max retries exceeded with url: /api/generate/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd525f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

That is localhost, not your IP.
Docker sees localhost as the container in which cat core is running. So find the ip of your machine and set it up as Ollama address

**Comment by valentimarco** [comment]
> If I Open Ollama and pull Zephyr through Terminal with (Ollama pull zephyr) and I put http://127.0.0.1:11434 in the Base URL and Zephyr in model. I start the chat and it gives me this error:
> 
> HTTPConnectionPool(host='127.0.0.1', port=11434): Max retries exceeded with url: /api/generate/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8f5fd525f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

We have open a issue to able to use localhost inside the container #524

**Comment by Leresyn** [comment]
Ok, the IP of my docker container with Ollama is, 172.17.0.2, I tried with this one and the cat starts thinking and after a few minutes he gives me this error: 
HTTPConnectionPool(host='172.17.0.2', port=11434): Max retries exceeded with url: /api/generate/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8f5fa327d0>, 'Connection to 172.17.0.2 timed out. (connect timeout=None)'))

**Comment by valentimarco** [comment]
No you need to up the machine ip. You can get it by using ifconfig (in linux) or ipconfig (in windows), after that find your internet card on the list (usually is only one but you can have more) and find the field `IPv4 Address`. Finally put the the ip addrress in the *base_url* like this `http://<ip-address-getted-from-ipconfig/ifconfig>:11434` (don't put the / after the port). If you need more help, switch the conversation on discord, bc this issue is closed!

**Comment by cleesmith** [comment]
On my MacBook Sonoma 14.3, i did this:
in a Terminal:
launchctl setenv OLLAMA_HOST "0.0.0.0"
- explanation here:
https://github.com/ollama/ollama/blob/main/docs/faq.md

- which allows this:
http://192.168.0.4:11434
- instead of:
http://localhost:11434 ... which does not work as seen above in the "max retries" message.

Which worked!  

This whole Docker approach seems very slow, but i don't this cat is for chat ... still learning.  Thanks.
