### ISSUE TITLE
[BUG] Admin page accessible from all addresses but functional only when opened from localhost

### ISSUE THREAD

**Issue by sambarza** [cheshire-cat-ai/core#589]
**Describe the bug**
The cat listen on 0.0.0.0 so is reachable from all the ip addresses, so the admin page is accessible from all the ip addresses, however is functional only when opened from localhost.

**To Reproduce**
Open the admin page from a browser on a different device where the cat is running.
The authentication popup appears asking for auth key.

**Expected behavior**
The admin page should be usable from all the devices in the network... correct?

**Idea**
The popup about authentication is misleading, the problem is that the admin page try to connect to "localhost".
Instead of inject the CORE_HOST, CORE_PORT, CORE_USE_SECURE_PROTOCOLS in the admin page, can we get them directly from the frontend using location.hostname, location.port, location.protocol?

In this way, by default, the admin page is usable everywhere in the network (for example by mobile). If someone split admin page and core to different servers can use CORE* environment variables to specify the address of the Cat.

**Comment by ethanlacerenza** [comment]
To resolve this issue in my local environment, I added an NGINX Docker container to load the entire environment over HTTPS with a custom certificate. Since NGINX is handling the reverse proxy, it is accessible from the entire network via HTTPS. However, this introduces a security concern. Therefore, I implemented basic authentication for NGINX to address this issue. I can also implement this for you, but I'm unsure if there is a login panel available or where to retrieve the auth key that is requested for hosts other than localhost.

@pieroit Is a login panel provided? Alternatively, how can the auth key be retrieved? I couldn't find information on this in the wiki.

If the auth key is provisioned, with a simple NGINX Docker setup, I can create the environment in HTTPS by including the provisioned auth key in the docker-compose file during deployment.

**Comment by pieroit** [comment]
@ethanlacerenza for the next few months we can assume the cat has no concept of user authentication, but there is a service encapsulating the cat, providing secure auth.

The cat can handle concurrent convos and keep memories separated, but for user login it is better to wait.

Let me know if you need clarifications :)
Thanks

P.S.: interesting your nginx solution! Maybe we can propose that to the community

**Comment by gerroon** [comment]
What is the auth key?

`docker run --rm -it -p 1865:80 ghcr.io/cheshire-cat-ai/core:latest`

![image](https://github.com/cheshire-cat-ai/core/assets/8519469/8c88241b-fadf-4280-aee3-9cc1ba6e50e8)
