### ISSUE TITLE
Speedup dependencies checks

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/core#609]
Every time the cat restarts it checks all plugin dependencies, taking a few seconds to do the checks. This is not a problem when starting the cat, but when developing (`DEBUG=true`) a restart occurs at every code change and at every plugin install / uninstall.

Is it possible to make `Plugin._install_requirements` faster or called only when necessary?

**Comment by kodaline** [comment]
> Thanks @kodaline, assigning also @Pingdred who is expert on this part

Great, I wanna be an expert as you @Pingdred so you will need to illuminate me with your knowledge 😸

**Comment by kodaline** [comment]
@pieroit me and @Pingdred has talked about this:
- we could use a flag `CHECK_PLUGIN_REQ_ON_BOOT` (or something shorter 😸 ) that:
  - if `TRUE`: everything is as it is at the moment
  - if `FALSE`: requirements check is done only on plugin activation

`PROS`:
- requirements check is limited only to a single plugin (the one you activate)

`CONS`:
- if a new requirement is added to a plugin (during development), the plugin needs to be activated again so that the requirements are checked again

A new issue will be opened for method `install_requirements`: instead of installing all the requirements, first check if the package is already installed, if so remove it from the requirements, and install only the needed packages
`Requirement from packaging.requirements` can be used to get the package name (`.name`)
and `importlib.util.find_spec(package_name)` can check if the package is already installed

**Comment by pieroit** [comment]
> @pieroit me and @Pingdred have talked about this:
> 
> * we could use a flag `CHECK_PLUGIN_REQ_ON_BOOT` (or something shorter 😸 ) that:
>   
>   * if `TRUE`: everything is as it is at the moment
>   * if `FALSE`: requirements check is done only on plugin activation

> `PROS`:
> 
> * requirements check is limited only to a single plugin (the one you activate)

Lovely!

> `CONS`:
> 
> * if a new requirement is added to a plugin (during development), the plugin needs to be activated again so that the requirements are checked again

No biggie, we can document this [here](https://cheshire-cat-ai.github.io/docs/technical/plugins/dependencies/), that when adding requirements you should deactivate and reactivate plugins

> A new issue will be opened for method `install_requirements`: instead of installing all the requirements, first check if the package is already installed, if so remove it from the requirements, and install only the needed packages `Requirement from packaging.requirements` can be used to get the package name (`.name`) and `importlib.util.find_spec(package_name)` can check if the package is already installed

I do not understand this sorry. Why removing?

> 
> EDIT: here [kodaline@2a2d679](https://github.com/kodaline/core/commit/2a2d6797816cbe5924d2aa9faac96ebec2dc0e41) is a wip, just a feasibility check, needs to be more discussed
> 
> note: this might impact admin page, to investigate further

Thanks

**Comment by kodaline** [comment]
@Pingdred  here https://github.com/kodaline/core/commit/daa2dc34e951fbbc2f91b6606e32dc5aeae398e6 the updated branch,
have fun testing with `pip freeze` performance for requirements check :)
