### ISSUE TITLE
[Feature] [Documentation] Better documentation for custom end-points

### ISSUE THREAD

**Issue by UBy** [cheshire-cat-ai/core#620]
Please add some example documentation for how to configure a custom end-point.

For example: If you have a OpenAI compatible end-point on OpenRouter you need to provide a model and an api key in the header.
I see an `options` column in the UI where I suppose I can put something, what what format should be used?

In **Autogen** I would simply provide everything like this:

```
    {
        "model": "<some-model>",
        "base_url": "https://openrouter.ai/api/v1", // Or other OpenAI compatible service
        "api_key": "<some-key>"
    }
```
How does that "translate" to this product?

**Comment by valentimarco** [comment]
Thx for the issue but this is the wrong repo because we have a [documentation repo](https://github.com/cheshire-cat-ai/docs) but I agree that needs a dedicated page, so recreate the issue in the documentation repo!
For the question: we have a article in our blog where we explain [how to do the adapter](https://cheshirecat.ai/custom-large-language-model/)

**Comment by pieroit** [comment]
> ```
>     {
>         "model": "<some-model>",
>         "base_url": "https://openrouter.ai/api/v1", // Or other OpenAI compatible service
>         "api_key": "<some-key>"
>     }
> ```
> 
> How does that "translate" to this product?

This issue is about OpenAI compatible services: 
https://github.com/cheshire-cat-ai/core/issues/604

So, coming soon :)
In the meantime just use llama-cpp-python, it also mocks OpenAI and should work with OpenRouter

**Comment by pieroit** [comment]
@UBy closing this issue, please follow #604
