### ISSUE TITLE
Replace sync request and I/O libs with async

### ISSUE THREAD

**Issue by alfredotoselli** [cheshire-cat-ai/core#945]
@lucagobbi 

Check `registry.py`

**Comment by lucagobbi** [comment]
As mentioned in the PR we have a bunch of blocking code here and there that should be migrated to async. However. we must be aware that async is not always good both for readability and for what the code does itself, putting async in front of any function definition is not a solution at all. 

Additionally we need to keep in mind how FastAPI handle these kind of stuff, because if we declare a route as async it will run it in the main event loop and if we insert blocking code in there it freeze the entire server. At that point we have two path ahead:
1. Declare our route as normal def without async so that FastAPI will run that in a threadpool.
2. Remove the blocking code and make the function really async (e.g. not using `requests` for http calls but use an async client like `httpx` or `aiohttp`)


Here some [docs](https://fastapi.tiangolo.com/async/#very-technical-details) about it, and [here](https://github.com/fastapi/fastapi/discussions/6946) a discussion in which they state that approach 2 performs better

The same happens with background tasks, all our ingestion pipeline is based on that feature. We should think about it as well. [Here](https://stackoverflow.com/questions/67599119/fastapi-asynchronous-background-tasks-blocks-other-requests) some discussions about this.

Hope you find these resources useful and we can further discuss this issue

**Comment by pieroit** [comment]
Let's stay on the threadpool until we have an actual measure of the worthyness of all this async.

Please give priority to devx (both ours and to the plugin developers)
If people want to scale, they can scale horizontally, the Cat is mostly for individuals and SME
